### ISSUE TITLE
Not working in 1.21

### ISSUE THREAD

**Issue by rexomi** [AV306/KeybindsGalore-Plus#2]
I cannot run on the newer version, but
 your fork is awesome, and I really hope you get success from it.

**Comment by AV306** [comment]
Hi rexomi, thank you so much for the support! 

I’ve got exams in a few weeks so I can’t really work on the mod much right now, but the 1.21 version will be coming really soon :)

**Comment by AV306** [comment]
Should be done with [v1.1.0+1.21](https://modrinth.com/mod/keybindsgaloreplus/version/1.1.0+1.21-alpha)!
