### ISSUE TITLE
Editable keybind description

### ISSUE THREAD

**Issue by Mo9713** [AV306/KeybindsGalore-Plus#3]
It would be cool to be able to edit the title/description of the keybind in the pie chart. Is that possible?

**Comment by AV306** [comment]
Yep, that should be doable!

How would you want to change them?

I’m thinking of using a file of keybind name overrides; a config GUI would be possible, but a lot of work (and I’d prefer not to use any libraries)

**Comment by customjack** [comment]
https://github.com/AV306/KeybindsGalore-Plus/blob/8c0254243554c70b3a0af670a0cfdeba510e4625/src/main/java/me/av306/keybindsgaloreplus/KeybindSelectorScreen.java#L227-L234

I'd imagine you'd attach a category name and translation key name as member variables to the action class. I think the simplest approach without adding a GUI is to have a command change these member variables. To keep a memory, you would need a file that initializes the appropriated actions with their category name and translation key name like you said. This would be translatable to a GUI if you ever wanted to add it. You'd want a whole manager class for this file too I'd imagine.

**Comment by AV306** [comment]
I’ve started work on this! Thanks for the suggestion :D

**Comment by AV306** [comment]
It's done! Keybind labels can be changed by creating the file "keybindsgaloreplus_customdata.data" and writing the following inside:

```
<translation key e.g. key.keybindsgaloreplus.reloadconfigs>:
custom_name=<custom name here>
```

This won't change the name displayed in the keybind menu; that (and by extension the displayed name in the pie menu) can be changed with a resource pack.
