### ISSUE TITLE
The ignored key is not working

### ISSUE THREAD

**Issue by Tgaisen** [AV306/KeybindsGalore-Plus#4]
I installed the Equipment Compare mod and updated KeybindsGalore Plus to version 1.2.0+1.21. After that, pressing the shift key in the game brings up the pie chart menu instead of allowing me to sneak. The game version is 1.21, fabric 0.16.0.

**Comment by AV306** [comment]
I've fixed this, thanks for pointing it out! The patched build (with the same version number) has been uploaded to Modrinth and GH releases, please let me know if it doesn't work :)
