### ISSUE TITLE
[Feature Request] Whitelist/Blacklist Keys

### ISSUE THREAD

**Issue by GhostIsBeHere** [AV306/KeybindsGalore-Plus#5]
I would like to be able to whitelist or blacklist certain keys from opening a radial menu, instead behaving as vanilla.

**Comment by AV306** [comment]
Whoops, sorry I missed this! This bugs me a lot too, I’m working on it right now :D

**Comment by AV306** [comment]
Hi, a blacklist feature has been added in 1.3.0-alpha! Please let me know if there are any issues with it :)

(also, by default it doesn’t behave *exactly* like vanilla; it does something like the KeybindsFix mod where it activates all bindings attached to the key at once) (this is configurable!)
