### ISSUE TITLE
KeybindsGalore Plus 1.21 not working

### ISSUE THREAD

**Issue by StarsShine11904** [AV306/KeybindsGalore-Plus#8]
KeybindsGalore Plus 1.21 Release does not work because the version is marked as 1.21.1

please fix this problem

https://mclo.gs/VTNiF9M

**Comment by AV306** [comment]
Thanks for the logs! I’ll fix this asap 👍

**Comment by AV306** [comment]
It should be [fixed now](https://modrinth.com/mod/keybindsgaloreplus/version/1.3.1+1.21.1)!
