### ISSUE TITLE
Key onlu functioning once

### ISSUE THREAD

**Issue by ClutchMasterYT** [AV306/KeybindsGalore-Plus#9]
whenever i load up my world and i press a key thats assigned to two commands, the first time, it works, but the second time some of the keys dont do the required function

**Comment by AV306** [comment]
Hi @ClutchMasterYT, could you provide me with details on your Minecraft version and KeybindsGalore+ version?

**Comment by AV306** [comment]
Hi, I can’t reproduce this issue, so I’m going to have to close it for now; please don’t hesitate to reopen it if it still happens!
